#!/usr/bin/env python3
# gen_div_edge.py -- directed divider edge-case test for the r9999 nu_divider
# port.  Emits a randgen-compatible .S (same 64-bit-mode startup + console-marker
# + break) that runs a fixed battery of div/divu/ddiv/ddivu corner cases and
# leaves each quotient/remainder in a GPR via mflo/mfhi.  ooo_core -c 1 compares
# GPRs per-retire, so every case is checked RTL-vs-interp as it executes.
#
#   ./gen_div_edge.py > div_edge.S ; make div_edge.elf
#   ../../ooo_core -f div_edge.elf -c 1 --maxicnt 5000000
import sys

M64 = 1 << 64
def u64(x):
    return x & (M64 - 1)

# (mnemonic, dividend, divisor).  Divisors are all NONZERO (MIPS div-by-zero is
# architecturally unpredictable -> RTL/interp needn't agree).  Values chosen to
# stress the CLZ skip: tiny/huge (quotient 0 -> underflow-to-PACK), x/1 (full
# width), x/x, small/small, huge/small, and the signed-overflow INT_MIN/-1.
CASES = [
    # 32-bit signed div
    ("div",  7, 3), ("div", -7, 3), ("div", 7, -3), ("div", -7, -3),
    ("div",  0, 5), ("div", 5, 1), ("div", 100, 100), ("div", 3, 1000000),
    ("div",  0x7fffffff, 2), ("div", 1000000, 3), ("div", -1, 2),
    ("div",  -2147483648, -1),                    # INT32_MIN / -1 (overflow, guarded)
    ("div",  0x7fffffff, 0x7fffffff),
    # 32-bit unsigned divu
    ("divu", 0xffffffff, 3), ("divu", 0xffffffff, 1), ("divu", 1, 0xffffffff),
    ("divu", 0x80000000, 2), ("divu", 0, 7), ("divu", 0xdeadbeef, 0x1234),
    # 64-bit signed ddiv
    ("ddiv", 7, 3), ("ddiv", -7, 3), ("ddiv", 0x7fffffffffffffff, 3),
    ("ddiv", -1, 2), ("ddiv", 1 << 62, 3), ("ddiv", 3, 1 << 40),
    ("ddiv", -(1 << 62), 7),
    ("ddiv", -(1 << 63), -1),                     # INT64_MIN / -1 (overflow, guarded)
    # 64-bit unsigned ddivu
    ("ddivu", 0xffffffffffffffff, 3), ("ddivu", 0xffffffffffffffff, 1),
    ("ddivu", 1, 0xffffffffffffffff), ("ddivu", 1 << 63, 3),
    ("ddivu", 0x123456789abcdef0, 0x1000), ("ddivu", 0xcafef00dbaadf00d, 7),
]

out = []
w = out.append
w("/* AUTO-GENERATED by gen_div_edge.py -- directed divider edge cases */")
w("    .set mips3")
w("    .set noreorder")
w("    .set noat")
w("    .text")
w("    .globl main")
w("    .type  main, @function")
w("main:")
w("    mfc0  $1, $12")
w("    ori   $1, $1, 0x80          /* Status.KX -> 64-bit mode */")
w("    mtc0  $1, $12")
w("    .word 0x000000c0            /* ehb */")
w("    multu $0, $0               /* init hi/lo */")
w("    lui   $9, %hi(div_edge_data)")
w("    ori   $9, $9, %lo(div_edge_data)")
w("    sll   $9, $9, 0            /* canonicalize base to 64-bit kseg0 */")
w("")
for i, (op, a, b) in enumerate(CASES):
    off = i * 16
    w("    /* [%2d] %-6s dividend=%#x divisor=%#x */" % (i, op, u64(a), u64(b)))
    w("    ld    $10, %d($9)" % (off + 0))
    w("    ld    $11, %d($9)" % (off + 8))
    w("    %-5s $0, $10, $11        /* raw divide (rd=$0), no trap macro */" % op)
    w("    mflo  $12               /* quotient  */")
    w("    mfhi  $13               /* remainder */")
w("")
w("    li    $25, 78")
w("    mtc0  $25, $7")
w("    li    $25, 69")
w("    mtc0  $25, $7")
w("    li    $25, 10")
w("    mtc0  $25, $7")
w("    break")
w("    .size main, .-main")
w("")
w("    .data")
w("    .align 3")
w("div_edge_data:")
for op, a, b in CASES:
    w("    .dword 0x%016x, 0x%016x" % (u64(a), u64(b)))
w("")
w("    .bss")
w("    .align 3")
w("randgen_scratch:")
w("    .space 1024")

sys.stdout.write("\n".join(out) + "\n")
